### ISSUE TITLE
Doesn’t work when the “Issues” link in the top bar is clicked

### ISSUE THREAD

**Issue by mathiasbynens** [sindresorhus/show-all-github-issues#3]
The “Issues” link on the right-hand sidebar (which points to e.g. `https://github.com/sindresorhus/github-issues-all/issues`) works fine, but when the “Issues” link in the top bar (which points to e.g. `https://github.com/sindresorhus/github-issues-all/issues?q=is%3Aopen+is%3Aissue` instead) is clicked, i.e. the one with the blue background in this screenshot:

![](http://i.imgur.com/HFltORu.png)

…then the plugin doesn’t take effect.

**Comment by MethodGrab** [comment]
I've just installed the Chrome extension and it doesn't seem to work from the right hand sidebar either. For me, it only works when I load an issues page directly, or refresh the page after clicking from the right hand sidebar.
