### ISSUE TITLE
No longer redirects on Chrome 46

### ISSUE THREAD

**Issue by joshuajabbour** [sindresorhus/show-all-github-issues#4]
This does not seem to work any longer. I'm running Chrome 46.0.2490.86 (64-bit). (No idea when it stopped working, as I just installed it.) But the redirect to `issues?q=is:open` doesn't occur.

When I get some time, I'll try to fix this. Opening an issue for future reference...

**Comment by sindresorhus** [comment]
It redirects fine for me (Chrome 54) when going directly to issues: https://github.com/sindresorhus/show-all-github-issues/issues Clicking the `Issues` tab never worked (#3).

**Comment by sindresorhus** [comment]
Confirmed. Help welcome :)
